services:
  esp32-idf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idf-dev
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev:rw
      - ./workspace:/home/developer/workspace
    environment:
      - DISPLAY=${DISPLAY}
    tty: true