services:
  esp32-idf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idf-dev
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority/:/root/.Xauthority
      - /dev:/dev:rw
      - type: bind
        source: ./workspace
        target: /home/developer/workspace
      - type: bind
        source: ./vscode/extensions
        target: /home/developer/.vscode-server/extensions
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ESP_WIFI_SSID=${ESP_WIFI_SSID}
      - ESP_WIFI_PASS=${ESP_WIFI_PASS}
